definitions:
  config:
    /hst:hst/hst:configurations/netpioneer.myangularhippo/hst:catalog:
      jcr:primaryType: hst:catalog
      /netpioneer.myangularhippo-catalog:
        jcr:primaryType: hst:containeritempackage
