definitions:
  config:
    /hst:hst/hst:configurations/netpioneer.myangularhippo/hst:sitemap:
      jcr:primaryType: hst:sitemap
      /root:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/homepage
        hst:refId: root
      /_any_:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/pagenotfound
      /pagenotfound:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/pagenotfound
        hst:refId: pagenotfound
      /news:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/news
      /contact:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/contact
