definitions:
  config:
    /hst:hst/hst:configurations/netpioneer.myangularhippo/hst:templates:
      jcr:primaryType: hst:templates
      /base-layout:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/netpioneer.myangularhippo/base-layout.ftl
      /base-top-menu:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/netpioneer.myangularhippo/base-top-menu.ftl
      /base-footer:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/netpioneer.myangularhippo/base-footer.ftl
      /homepage-main:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/netpioneer.myangularhippo/homepage-main.ftl
      /pagenotfound-main:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/netpioneer.myangularhippo/pagenotfound-main.ftl
      /news-main:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/netpioneer.myangularhippo/news-main.ftl
      /contact-main:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/netpioneer.myangularhippo/contact-main.ftl
