definitions:
  config:
    /hst:hst/hst:configurations/netpioneer.myangularhippo/hst:pages/contact:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:component
        hst:template: contact-main
